--1. Display the number of states present in the LocationTable
select count(state) from location


--2. How many products are of regular type?
select count(*) from product
where type = 'regular'


--3. How much spending has been done on marketing of product ID 1?
select sum(marketing) as sum_Id1 from fact
where productId = 1


--4. What is the minimum sales of a product?
select min(sales) as min_sales from fact


--5. Display the max Cost of Good Sold (COGS).
select max(COGS) as maxCOGS from fact


--6. Display the details of the product where product type is coffee.
select * from product
where product_Type = 'coffee'


--7. Display the details where total expenses are greater than 40. 
select * from fact 
where Total_Expenses > 40



--8. What is the average sales in area code 719?
select avg(sales) from fact
where Area_Code = 719



--9. Find out the total profit generated by Colorado state.
select sum(profit) as Profit_Sum from fact as f
join location as l on f.Area_Code = l.Area_Code
where l.state = 'colorado'



--10. Display the average inventory for each product ID.
select productID,avg(Inventory) as avgInventory from fact
group by productID
order by productId



--11. Display state in a sequential order in a Location Table.
select distinct state from location
order by state



--12. Display the average budget of the Product where the average budget margin should be greater than 100.
select p.Product, avg(budget_Margin) as avg_Budget from fact as f
join product as p on f.productId = p.productId
group by p.product
having avg(budget_Margin) > 100



--13. What is the total sales done on date 2010-01-01?
select sum(sales) as Total_Sales from fact
where date = '2010-01-01'



--14. Display the average total expense of each product ID on an individual date. 
select date, productId, avg(Total_Expenses) as AvgExpenses from fact
group by date, ProductId
order by  date,productID



--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
select f.date, p.productID, p.product_type, p.product, f.sales, f.profit, l.state, l.area_code 
from fact as f
join location as l on f.Area_Code  = l.Area_Code
join product as p on p.ProductId = f.ProductId



--16. Display the rank without any gap to show the sales wise rank.
select sales, DENSE_RANK()over(order by sales) as ranks
from fact



--17. Find the state wise profit and sales. 
select l.state, sum(f.profit) as TotalProfit, sum(f.sales) as Total_Sales
from fact as f
join location as l on f.Area_Code  = l.Area_Code
group by l.State



--18. Find the state wise profit and sales along with the productname.
select l.state,product, sum(f.profit) as TotalProfit, sum(f.sales) as Total_Sales
from fact as f
join product as p on p.ProductId = f.ProductId
join location as l on f.Area_Code  = l.Area_Code
group by l.State,product



--19. If there is an increase in sales of 5%, calculate the increasedsales.
select sales, sales*1.05 as increasedsales from fact



--20. Find the maximum profit along with the product ID and producttype.
select p.ProductId,p.Product_Type, max(f.profit) as maxProfit from product as p
join fact as f on p.ProductId = f.ProductId
group by p.ProductId,p.Product_Type



--21. Create a stored procedure to fetch the result according to the product typefrom Product Table. 
Create procedure Fetch_AllResult
as
begin
select * from  product
order by Product_Type
end

exec Fetch_AllResult



--22. Write a query by creating a condition in which if the total expenses is lessthan 60 then it is a profit or else loss. 
select  Total_Expenses, 
      case
      when Total_Expenses < 60 then 'profit'
      else 'loss'
      end as Review
from fact


--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.

SELECT 
    ProductID,
    date,
    DATEPART(WEEK, Date) AS Week_No,
    SUM(Sales) AS Weekly_Sales
FROM fact
GROUP BY ROLLUP(ProductID, DATEPART(WEEK, Date),date);
SELECT ProductID, Date, SUM(Sales)
FROM fact
GROUP BY ROLLUP(ProductID,Date);


--24. Apply union and intersection operator on the tables which consist of attribute area code. 
select Area_Code from fact
union
select Area_Code from Location

select Area_Code from fact
intersect
select Area_Code from Location



--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.
create function ProductByType (@producttype varchar(50))
returns table
as
return
(
select * from Product
where Product_Type = @producttype
)

select * from dbo.ProductByType('coffee')



--26. Change the product type from coffee to tea where product IDis 1 andundoit. 
begin transaction 

update Product
set Product_Type = 'tea'
where Product_Type = 'coffee'

select * from product
where Product_Type = 'Tea'

rollback



--27. Display the date, product ID and sales where total expenses are between 100 to 200. 
select date,ProductId,sales from fact
where Total_Expenses between 100 and 200



--28. Delete the records in the Product Table for regular type.
delete from product
where type = 'Regular'

select * from product



--29. Display the ASCII value of the fifth character from the columnProduct
select ascii(substring(product, 5, 1)) as FifthCharASCII 
from product